### ISSUE TITLE
update `input_data_last_updated`

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nwp-consumer#52] opened 2023-10-04 07:13 UTC
## Detailed Description
The old consumer updates the `input_data_last_updated` using `from nowcasting_datamodel.read.read import update_latest_input_data_last_updated` but the new one doesnt. 
I do like how clean the new nwp-consumer is so, its probrbaly best we dont add it in there

## Context
- new nwp consumer in 2023-09

## Possible Implementation
- we could add the small function into airflow with pure python code

**Comment by peterdudfield** [comment] 2023-10-04 07:14
What do you think @devsjc

**Comment by devsjc** [comment] 2023-10-04 10:05
Duplicate of https://github.com/openclimatefix/ocf-infrastructure/issues/299?

**Closed** 2023-10-04 10:14 UTC
Labels: discussion
